### ISSUE TITLE
Copy from Example but crash

### ISSUE THREAD

**Issue by JeromeTW** [charliewilliams/CWNotificationBanner#4]
hello, I installed through cocoa pods.
my Xcode is Version 7.3 (7D175)

This is my code:
override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        let message = Message(text: "You have an alert")
        NotificationBanner.showMessage(message)
    }
but i get: fatal error: unexpectedly found nil while unwrapping an Optional value.
And I trying to track the bug, it always crash at NotificationBanner.swift line:234
`override public var barTintColor: UIColor? {
        didSet {
            underStatusBarView.backgroundColor = barTintColor?.colorWithAlphaComponent(0.85)
        }
    }`
It's my first time to post something here, and i don't know how to insert code and image correctly, sorry for everyone.
Can anybody help me?

**Comment by lockys** [comment]
I faced this problem too.
I changed the following code 

``` swift
public static var sharedToolbar: NotificationBanner = {
        let bundle = NSBundle(forClass: NotificationBanner.classForCoder())
        let t = bundle.loadNibNamed(String(NotificationBanner), owner: nil, options: nil).first as! NotificationBanner
        t.hideHairlineBorder()
        t.barTintColor = UIColor(white: 0.2, alpha: 0.4)
        t.addStatusBarBackingView()
        UIApplication.sharedApplication().keyWindow?.addSubview(t)
        return t
}()
```

to

``` swift
public static var sharedToolbar: NotificationBanner = {
        let bundle = NSBundle(forClass: NotificationBanner.classForCoder())
        let t = bundle.loadNibNamed(String(NotificationBanner), owner: nil, options: nil).first as! NotificationBanner
        t.hideHairlineBorder()
        t.addStatusBarBackingView()
        t.barTintColor = UIColor(white: 0.2, alpha: 0.4)
        UIApplication.sharedApplication().keyWindow?.addSubview(t)
        return t
}()
```

It works, I guess the problem is caused by the `underStatusBarView` is `nil`.
So the `underStatusBarView` should be initialized first.
I do not know if it is a true way to solve this problem.
Wait for @charliewilliams 's reply.

**Comment by charliewilliams** [comment]
Yeah, this is a good way to solve that problem! Thanks for it— I don't know why it didn't come up for me before as it now seems sort of obvious :/ Could you submit a pull request and I'll accept it?
